---
- hosts: my_hosts
  become: yes
  roles:
   - role_java
   
  tasks:
  - name: copy
    copy:
      src: ./target/devops-1.0.war
      dest: /home/pileUser/
  - name: deploy and launch war
    shell:
      cmd: 'java -jar /home/pileUser/devops-1.0.war &'
      #cmd: 'ssh -T pileUser@40.114.211.179 -p22 -f "java -jar /home/pileUser/devops-1.0.war"'
       
